# frozen_string_literal: true

require_relative 'format_registry_bootstrap'

module Shoko
  module Bootstrap
        module RuntimeBootstrap
          FEATURES = %w[
            shoko/shared/namespaces
            shoko/core/validator
            shoko/adapters/monitoring/logger_adapter
            shoko/adapters/monitoring/performance_monitor
            shoko/adapters/runtime/env_runtime_config_adapter
            shoko/adapters/runtime/null_runtime_config
            shoko/adapters/runtime/rexml_security_limits_adapter
            shoko/adapters/runtime/process_control_adapter
            shoko/adapters/runtime/monotonic_clock_adapter
            shoko/adapters/runtime/session_state/event_bus
            shoko/adapters/runtime/session_state/state_store
            shoko/adapters/runtime/session_state/observer_state_store
            shoko/adapters/storage/cache_pointer_manager
            shoko/adapters/storage/cache_availability_adapter
            shoko/adapters/storage/book_cache_pipeline
            shoko/adapters/book_sources/document_service
            shoko/adapters/storage/pagination_cache
            shoko/adapters/book_sources/library_scanner
            shoko/application/services/pagination/pagination_cache_preloader
            shoko/core/book_formats/format_registry
            shoko/core/book_formats/epub/xhtml_content_parser
            shoko/adapters/book_sources/epub/epub_importer
            shoko/core/book_formats/fb2/fb2_inline_parser
            shoko/core/book_formats/fb2/fb2_section_flattener
            shoko/core/book_formats/fb2/fb2_metadata_extractor
            shoko/core/book_formats/fb2/fb2_content_parser
            shoko/adapters/book_sources/fb2/fb2_importer
            shoko/core/book_formats/kindle/exth_parser
            shoko/core/book_formats/kindle/mobi_header_parser
            shoko/core/book_formats/kindle/palmdoc_decompressor
            shoko/core/book_formats/kindle/pdb_header_parser
            shoko/core/book_formats/kindle/kindle_metadata_extractor
            shoko/core/book_formats/kindle/kindle_content_parser
            shoko/adapters/book_sources/kindle/kindle_importer
            shoko/core/book_formats/pdf/pdf_reader
            shoko/core/book_formats/pdf/pdf_text_extractor
            shoko/core/book_formats/pdf/pdf_metadata_extractor
            shoko/core/book_formats/pdf/pdf_content_parser
            shoko/adapters/book_sources/pdf/pdf_importer
            shoko/core/book_formats/rtf/rtf_parser
            shoko/core/book_formats/rtf/rtf_metadata_extractor
            shoko/core/book_formats/rtf/rtf_content_parser
            shoko/adapters/book_sources/rtf/rtf_importer
            shoko/shared/errors
            shoko/shared/optional_dependency
            shoko/core/models/reader_settings
            shoko/adapters/ui/constants/ui_constants
            shoko/adapters/ui/constants/themes
            shoko/adapters/ui/constants/messages
            shoko/adapters/ui/constants/highlighting
            shoko/adapters/ui/rendering/models/page_rendering_context
            shoko/adapters/ui/rendering/models/rendering_context
            shoko/adapters/ui/rendering/models/line_geometry
            shoko/core/models/selection_anchor
            shoko/adapters/ui/builders/page_setup_builder
            shoko/shared/version
            shoko/adapters/output/terminal/terminal
            shoko/adapters/input/validators/file_path_validator
            shoko/adapters/input/validators/terminal_size_validator
            shoko/adapters/book_sources/book_finder
            shoko/adapters/storage/recent_files
            shoko/adapters/book_sources/book_document
            shoko/adapters/output/terminal/text_metrics
            shoko/adapters/output/terminal/text_metrics_port_adapter
            shoko/adapters/output/kitty/display_capabilities
            shoko/adapters/input/command_factory
            shoko/adapters/input/annotations/mouse_handler
            shoko/bootstrap/dependency_container
            shoko/bootstrap/container_factory
            shoko/core/models/book_data
            shoko/core/models/chapter
            shoko/core/models/bookmark
            shoko/core/models/bookmark_data
            shoko/core/models/toc_entry
            shoko/core/models/content_block
            shoko/core/ports/outbound/bookmark_repository
            shoko/core/ports/outbound/annotation_repository
            shoko/core/ports/outbound/cache_manager
            shoko/core/ports/outbound/cache_pointer_resolver
            shoko/core/ports/outbound/cache_availability
            shoko/core/ports/outbound/dictionary_availability
            shoko/core/ports/outbound/metadata_reader
            shoko/core/ports/outbound/recent_files_repository
            shoko/core/ports/outbound/event_publisher
            shoko/core/ports/outbound/text_sanitizer
            shoko/core/ports/outbound/text_metrics
            shoko/core/ports/outbound/display_capabilities
            shoko/core/ports/outbound/instrumentation
            shoko/core/ports/outbound/async_executor
            shoko/core/ports/outbound/observer_registry
            shoko/core/ports/outbound/wrapped_lines_provider
            shoko/core/ports/outbound/render_state_writer
            shoko/core/ports/inbound/command_bus
            shoko/core/events/base_domain_event
            shoko/core/events/bookmark_events
            shoko/core/events/annotation_events
            shoko/core/events/progress_events
            shoko/core/events/domain_event_bus
            shoko/adapters/storage/repositories/base_repository
            shoko/adapters/storage/repositories/bookmark_repository
            shoko/adapters/storage/repositories/annotation_repository
            shoko/adapters/storage/repositories/progress_repository
            shoko/core/services/base_service
            shoko/core/services/default_text_metrics
            shoko/core/services/default_display_capabilities
            shoko/core/services/null_instrumentation
            shoko/core/services/inline_executor
            shoko/application/services/reader/navigation_service
            shoko/application/services/reader/navigation/context_helpers
            shoko/application/services/reader/bookmark_service
            shoko/application/services/reader/annotation_state_service
            shoko/core/services/page_calculator_service
            shoko/core/services/coordinate_service
            shoko/core/services/layout_service
            shoko/adapters/output/clipboard/clipboard_service
            shoko/core/services/annotation_service
            shoko/core/services/in_book_search_service
            shoko/adapters/output/terminal/terminal_service
            shoko/core/services/selection_service
            shoko/adapters/output/formatting/wrapping_service
            shoko/adapters/output/formatting/formatting_service
            shoko/adapters/ui/component_factory
            shoko/adapters/output/notification_service
            shoko/adapters/storage/cache_pointer_resolver
            shoko/adapters/storage/recent_files_repository
            shoko/application/use_cases/catalog_service
            shoko/application/use_cases/settings_service
            shoko/application/use_cases/command_bus
            shoko/adapters/book_sources/download_service
            shoko/application/use_cases/commands/base_command
            shoko/application/use_cases/commands/navigation_commands
            shoko/application/use_cases/commands/bookmark_commands
            shoko/adapters/runtime/session_state/actions/base_action
            shoko/adapters/runtime/session_state/actions/update_state_action
            shoko/adapters/runtime/session_state/actions/toggle_view_mode_action
            shoko/adapters/runtime/session_state/actions/switch_reader_mode_action
            shoko/adapters/runtime/session_state/actions/quit_to_menu_action
            shoko/adapters/runtime/session_state/actions/update_message_action
            shoko/adapters/runtime/session_state/actions/update_config_action
            shoko/adapters/runtime/session_state/actions/update_sidebar_action
            shoko/adapters/runtime/session_state/actions/update_rendered_lines_action
            shoko/adapters/runtime/session_state/actions/update_ui_loading_action
            shoko/adapters/runtime/session_state/actions/update_pagination_state_action
            shoko/adapters/runtime/session_state/actions/update_reader_meta_action
            shoko/adapters/runtime/session_state/actions/update_menu_action
            shoko/adapters/runtime/session_state/event_publisher_adapter
            shoko/adapters/runtime/session_state/observer_registry_adapter
            shoko/adapters/runtime/session_state/selectors/reader_selectors
            shoko/adapters/runtime/session_state/selectors/menu_selectors
            shoko/adapters/runtime/session_state/selectors/config_selectors
            shoko/adapters/ui/sessions/session_outcome
            shoko/adapters/ui/view_models/reader_view_model
            shoko/application/unified_application
            shoko/adapters/ui/view_models/reader_view_model_builder
            shoko/application/reader_startup_orchestrator
            shoko/adapters/ui/rendering/frame_coordinator
            shoko/adapters/ui/rendering/render_pipeline
            shoko/application/services/pagination/page_info_calculator
            shoko/application/services/pagination/pagination_orchestrator
            shoko/application/services/pagination/pagination_coordinator
            shoko/adapters/ui/rendering/reader_render_coordinator
            shoko/application/reader_lifecycle
            shoko/core/services/progress_helper
            shoko/adapters/input/controllers/ui_controller
            shoko/adapters/input/controllers/state_controller
            shoko/adapters/input/reader_input_controller
            shoko/adapters/ui/rendering/views/base_view_renderer
            shoko/adapters/ui/rendering/views/split_view_renderer
            shoko/adapters/ui/rendering/views/single_view_renderer
            shoko/adapters/ui/rendering/views/help_renderer
            shoko/adapters/ui/rendering/views/view_renderer_factory
            shoko/adapters/ui/components/screens/base_screen_component
            shoko/adapters/ui/components/screens/menu_screen_component
            shoko/adapters/ui/components/screens/annotation_detail_screen_component
            shoko/adapters/ui/components/screens/annotation_editor_screen_component
            shoko/adapters/ui/components/annotation_editor_overlay_component
            shoko/adapters/input/controllers/menu/controller
            shoko/adapters/input/controllers/mouseable_reader
            shoko/adapters/input/cli
          ].freeze

          module_function

          def boot!
            return if @booted

            FEATURES.each { |feature| require feature }
            FormatRegistryBootstrap.register!
            @booted = true
          end
        end
      end
end
